version: '3'

services:
  
  # activemq:
  #   container_name: activemq
  #   image: masstransit/activemq
  #   ports:
  #     - 61616:61616
  #     - 61617:5672
  #     - 8161:8161

  artemis0:
    container_name: artemis0
    image: artemis-ubuntu1
    ports:
      - "8161:8161"
      - "61616:61616"
    #volumes:      
    #  - ./broker/server-1:/var/lib/artemis-instance
    environment:
      EXTRA_ARGS: "--default-port 61616 --clustered --host artemis0 --http-host artemis0 --relax-jolokia"

  artemis1:
    container_name: artemis1
    image: artemis-ubuntu1
    ports:
      - "8162:8161"
      - "9999:61616"
    #volumes:      
    #  - ./broker/server-1:/var/lib/artemis-instance
    environment:
      EXTRA_ARGS: "--default-port 61616 --clustered --host artemis1 --http-host artemis1 --relax-jolokia" 